version: "3.8"

services:
  generate_fetus_grpc_server:
    build:
      context: ./generate_fetus_grpc
      dockerfile: Dockerfile
    expose:
      - "50051"
    env_file:
      - ./generate_fetus_grpc/.env
    container_name: generate_fetus_grpc_server
    command: python3 src/main.py

  api_gateway_server:
    build:
      context: ./api_gate_way
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./api_gate_way/.env
    depends_on:
      - generate_fetus_grpc_server
    container_name: api_gateway_server
    command: npm run start:prod
