# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/generate-fetus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/generate-fetus.proto\x12\x0egenerate_fetus\"4\n%GenerateFetusGRPCOutboundPortInputDto\x12\x0b\n\x03url\x18\x01 \x01(\t\"5\n&GenerateFetusGRPCOutboundPortOutputDto\x12\x0b\n\x03url\x18\x01 \x01(\t2\x9c\x01\n\x14GenerateFetusService\x12\x83\x01\n\x12generateFetusImage\x12\x35.generate_fetus.GenerateFetusGRPCOutboundPortInputDto\x1a\x36.generate_fetus.GenerateFetusGRPCOutboundPortOutputDtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.generate_fetus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GENERATEFETUSGRPCOUTBOUNDPORTINPUTDTO']._serialized_start=46
  _globals['_GENERATEFETUSGRPCOUTBOUNDPORTINPUTDTO']._serialized_end=98
  _globals['_GENERATEFETUSGRPCOUTBOUNDPORTOUTPUTDTO']._serialized_start=100
  _globals['_GENERATEFETUSGRPCOUTBOUNDPORTOUTPUTDTO']._serialized_end=153
  _globals['_GENERATEFETUSSERVICE']._serialized_start=156
  _globals['_GENERATEFETUSSERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
