# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.interface.proto import chatbot_pb2 as proto_dot_chatbot__pb2


class ChatbotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFetusResponseFromChatbot = channel.unary_unary(
            "/chatbot.ChatbotService/getFetusResponseFromChatbot",
            request_serializer=proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortInputDto.SerializeToString,
            response_deserializer=proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortOutputDto.FromString,
        )


class ChatbotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFetusResponseFromChatbot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getFetusResponseFromChatbot": grpc.unary_unary_rpc_method_handler(
            servicer.getFetusResponseFromChatbot,
            request_deserializer=proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortInputDto.FromString,
            response_serializer=proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortOutputDto.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chatbot.ChatbotService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ChatbotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFetusResponseFromChatbot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chatbot.ChatbotService/getFetusResponseFromChatbot",
            proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortInputDto.SerializeToString,
            proto_dot_chatbot__pb2.GetFetusResponseFromChatbotOutboundPortOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
